services:
  app:
    build: .
    container_name: students_app
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
      - ./logs:/app/logs
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres
    container_name: students_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d students" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge