"""add faculty with default value

Revision ID: 47eed6bf2a76
Revises: e76546e4a750
Create Date: 2025-02-22 13:45:04.856757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47eed6bf2a76'
down_revision: Union[str, None] = 'e76546e4a750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Вставка факультета с использованием SQL
    op.execute("INSERT INTO faculties (name) VALUES ('Факультет информатики')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление факультета с использованием SQL
    op.execute("DELETE FROM faculties WHERE name = 'Факультет информатики'")
    # ### end Alembic commands ###
